import Navbar from '@/Components/Navbar/Navbar'

import './globals.css'
import { Inter } from 'next/font/google'
// import { useEffect } from 'react';
// import AOS from 'aos';
// import 'aos/dist/aos.css';

const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Hotel Management',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  //  useEffect(() => {
  //   AOS.init({
  //     duration:800,
  //     once:false
  //   });
  // }, []);
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}</body>
    </html>
  )
}
